### ISSUE TITLE
Can't understand

### ISSUE THREAD

**Issue by TimChen44** [rwaldron/exponentiation-operator#11]
let cubed = 2 *\* 3;
// same as: 2 \* 2 \* 2

Why not use：
let cubed = 2 ^ 3;
This is more in line with mathematical formulas.

**Comment by zloirock** [comment]
[xor](http://www.ecma-international.org/ecma-262/6.0/#sec-binary-bitwise-operators), `2 ^ 3 === 1`.

**Comment by lv7777** [comment]
python,perl,ruby...etc is used **
