### ISSUE TITLE
Why is exponential operator under UnaryExpression?

### ISSUE THREAD

**Issue by RReverser** [rwaldron/exponentiation-operator#9]
I understand that this might be a bit easier to inject it there, but doesn't it break clarity of names of syntactic constructs?

**Comment by claudepache** [comment]
The reason is that we want the exponential operator to have the same precedence level as the unary minus operator, with right-to-left associative order, so that `-x**-y` is interpreted correctly as 
`-(x**(-y))`.

The obvious solution to the naming issue is to rename UnaryExpression into something else.

**Comment by RReverser** [comment]
Not necessarily rename - UnaryExpression is a pretty good name for, well, unary expressions. Could be split into two rules + another that groups them.

**Comment by claudepache** [comment]
That would just add one or two additional productions that would be used only once. Is there a benefit to have a separate production for the sake of its name? Given the high number of productions the current complete grammar already has, I would personally strive to _reduce_ the number of rules when possible.

**Comment by RReverser** [comment]
@claudepache Well, at work I currently use machine-readable productions (in particular, grammar) from spec in order to generate "perfect DSL" and properly tokenize JavaScript. Changes to names break assumptions, especially when done on such ground names that existed through-out several versions of spec. But I understand that my case might be rather rare.
